<?php
  
  namespace Database\Seeders;

  use Illuminate\Database\Console\Seeds\WithoutModelEvents;
  use Illuminate\Database\Seeder;
  use App\Models\Author;
  use App\Models\Country;
  use App\Models\People;
  use App\Models\Book;
  use \Faker\Generator;
  use App\Models\Category;

  
class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = Country::create(['name' => 'Afghanistan', 'iso' => 'AF']);
        $countries->create(['name' => 'Åland Islands', 'iso' => 'AX']);
        $countries->create(['name' => 'Albania', 'iso' => 'AL']);
        $countries->create(['name' => 'Algeria', 'iso' => 'DZ']);
        $countries->create(['name' => 'American Samoa', 'iso' => 'AS']);
        $countries->create(['name' => 'Andorra', 'iso' => 'AD']);
        $countries->create(['name' => 'Angola', 'iso' => 'AO']);
        $countries->create(['name' => 'Anguilla', 'iso' => 'AI']);
        $countries->create(['name' => 'Antarctica', 'iso' => 'AQ']);
        $countries->create(['name' => 'Antigua and Barbuda', 'iso' => 'AG']);
        $countries->create(['name' => 'Argentina', 'iso' => 'AR']);
        $countries->create(['name' => 'Armenia', 'iso' => 'AM']);
        $countries->create(['name' => 'Aruba', 'iso' => 'AW']);
        $countries->create(['name' => 'Australia', 'iso' => 'AU']);
        $countries->create(['name' => 'Austria', 'iso' => 'AT']);
        $countries->create(['name' => 'Azerbaijan', 'iso' => 'AZ']);
        $countries->create(['name' => 'Bahamas', 'iso' => 'BS']);
        $countries->create(['name' => 'Bahrain', 'iso' => 'BH']);
        $countries->create(['name' => 'Bangladesh', 'iso' => 'BD']);
        $countries->create(['name' => 'Barbados', 'iso' => 'BB']);
        $countries->create(['name' => 'Belarus', 'iso' => 'BY']);
        $countries->create(['name' => 'Belgium', 'iso' => 'BE']);
        $countries->create(['name' => 'Belize', 'iso' => 'BZ']);
        $countries->create(['name' => 'Benin', 'iso' => 'BJ']);
        $countries->create(['name' => 'Bermuda', 'iso' => 'BM']);
        $countries->create(['name' => 'Bhutan', 'iso' => 'BT']);
        $countries->create(['name' => 'Bolivia, Plurinational State of', 'iso' => 'BO']);
        $countries->create(['name' => 'Bonaire, Sint Eustatius and Saba', 'iso' => 'BQ']);
        $countries->create(['name' => 'Bosnia and Herzegovina', 'iso' => 'BA']);
        $countries->create(['name' => 'Botswana', 'iso' => 'BW']);
        $countries->create(['name' => 'Bouvet Island', 'iso' => 'BV']);
        $countries->create(['name' => 'Brazil', 'iso' => 'BR']);
        $countries->create(['name' => 'British Indian Ocean Territory', 'iso' => 'IO']);
        $countries->create(['name' => 'Brunei Darussalam', 'iso' => 'BN']);
        $countries->create(['name' => 'Bulgaria', 'iso' => 'BG']);
        $countries->create(['name' => 'Burkina Faso', 'iso' => 'BF']);
        $countries->create(['name' => 'Burundi', 'iso' => 'BI']);
        $countries->create(['name' => 'Cambodia', 'iso' => 'KH']);
        $countries->create(['name' => 'Cameroon', 'iso' => 'CM']);
        $countries->create(['name' => 'Canada', 'iso' => 'CA']);
        $countries->create(['name' => 'Cape Verde', 'iso' => 'CV']);
        $countries->create(['name' => 'Cayman Islands', 'iso' => 'KY']);
        $countries->create(['name' => 'Central African Republic', 'iso' => 'CF']);
        $countries->create(['name' => 'Chad', 'iso' => 'TD']);
        $countries->create(['name' => 'Chile', 'iso' => 'CL']);
        $countries->create(['name' => 'China', 'iso' => 'CN']);
        $countries->create(['name' => 'Christmas Island', 'iso' => 'CX']);
        $countries->create(['name' => 'Cocos (Keeling) Islands', 'iso' => 'CC']);
        $countries->create(['name' => 'Colombia', 'iso' => 'CO']);
        $countries->create(['name' => 'Comoros', 'iso' => 'KM']);
        $countries->create(['name' => 'Congo', 'iso' => 'CG']);
        $countries->create(['name' => 'Congo, the Democratic Republic of the', 'iso' => 'CD']);
        $countries->create(['name' => 'Cook Islands', 'iso' => 'CK']);
        $countries->create(['name' => 'Costa Rica', 'iso' => 'CR']);
        $countries->create(['name' => 'Côte d\'Ivoire', 'iso' => 'CI']);
        $countries->create(['name' => 'Croatia', 'iso' => 'HR']);
        $countries->create(['name' => 'Cuba', 'iso' => 'CU']);
        $countries->create(['name' => 'Curaçao', 'iso' => 'CW']);
        $countries->create(['name' => 'Cyprus', 'iso' => 'CY']);
        $countries->create(['name' => 'Czech Republic', 'iso' => 'CZ']);
        $countries->create(['name' => 'Denmark', 'iso' => 'DK']);
        $countries->create(['name' => 'Djibouti', 'iso' => 'DJ']);
        $countries->create(['name' => 'Dominica', 'iso' => 'DM']);
        $countries->create(['name' => 'Dominican Republic', 'iso' => 'DO']);
        $countries->create(['name' => 'Ecuador', 'iso' => 'EC']);
        $countries->create(['name' => 'Egypt', 'iso' => 'EG']);
        $countries->create(['name' => 'El Salvador', 'iso' => 'SV']);
        $countries->create(['name' => 'Equatorial Guinea', 'iso' => 'GQ']);
        $countries->create(['name' => 'Eritrea', 'iso' => 'ER']);
        $countries->create(['name' => 'Estonia', 'iso' => 'EE']);
        $countries->create(['name' => 'Ethiopia', 'iso' => 'ET']);
        $countries->create(['name' => 'Falkland Islands (Malvinas)', 'iso' => 'FK']);
        $countries->create(['name' => 'Faroe Islands', 'iso' => 'FO']);
        $countries->create(['name' => 'Fiji', 'iso' => 'FJ']);
        $countries->create(['name' => 'Finland', 'iso' => 'FI']);
        $countries->create(['name' => 'France', 'iso' => 'FR']);
        $countries->create(['name' => 'French Guiana', 'iso' => 'GF']);
        $countries->create(['name' => 'French Polynesia', 'iso' => 'PF']);
        $countries->create(['name' => 'French Southern Territories', 'iso' => 'TF']);
        $countries->create(['name' => 'Gabon', 'iso' => 'GA']);
        $countries->create(['name' => 'Gambia', 'iso' => 'GM']);
        $countries->create(['name' => 'Georgia', 'iso' => 'GE']);
        $countries->create(['name' => 'Germany', 'iso' => 'DE']);
        $countries->create(['name' => 'Ghana', 'iso' => 'GH']);
        $countries->create(['name' => 'Gibraltar', 'iso' => 'GI']);
        $countries->create(['name' => 'Greece', 'iso' => 'GR']);
        $countries->create(['name' => 'Greenland', 'iso' => 'GL']);
        $countries->create(['name' => 'Grenada', 'iso' => 'GD']);
        $countries->create(['name' => 'Guadeloupe', 'iso' => 'GP']);
        $countries->create(['name' => 'Guam', 'iso' => 'GU']);
        $countries->create(['name' => 'Guatemala', 'iso' => 'GT']);
        $countries->create(['name' => 'Guernsey', 'iso' => 'GG']);
        $countries->create(['name' => 'Guinea', 'iso' => 'GN']);
        $countries->create(['name' => 'Guinea-Bissau', 'iso' => 'GW']);
        $countries->create(['name' => 'Guyana', 'iso' => 'GY']);
        $countries->create(['name' => 'Haiti', 'iso' => 'HT']);
        $countries->create(['name' => 'Heard Island and McDonald Mcdonald Islands', 'iso' => 'HM']);
        $countries->create(['name' => 'Holy See (Vatican City State)', 'iso' => 'VA']);
        $countries->create(['name' => 'Honduras', 'iso' => 'HN']);
        $countries->create(['name' => 'Hong Kong', 'iso' => 'HK']);
        $countries->create(['name' => 'Hungary', 'iso' => 'HU']);
        $countries->create(['name' => 'Iceland', 'iso' => 'IS']);
        $countries->create(['name' => 'India', 'iso' => 'IN']);
        $countries->create(['name' => 'Indonesia', 'iso' => 'ID']);
        $countries->create(['name' => 'Iran, Islamic Republic of', 'iso' => 'IR']);
        $countries->create(['name' => 'Iraq', 'iso' => 'IQ']);
        $countries->create(['name' => 'Ireland', 'iso' => 'IE']);
        $countries->create(['name' => 'Isle of Man', 'iso' => 'IM']);
        $countries->create(['name' => 'Israel', 'iso' => 'IL']);
        $countries->create(['name' => 'Italy', 'iso' => 'IT']);
        $countries->create(['name' => 'Jamaica', 'iso' => 'JM']);
        $countries->create(['name' => 'Japan', 'iso' => 'JP']);
        $countries->create(['name' => 'Jersey', 'iso' => 'JE']);
        $countries->create(['name' => 'Jordan', 'iso' => 'JO']);
        $countries->create(['name' => 'Kazakhstan', 'iso' => 'KZ']);
        $countries->create(['name' => 'Kenya', 'iso' => 'KE']);
        $countries->create(['name' => 'Kiribati', 'iso' => 'KI']);
        $countries->create(['name' => 'Korea, Democratic People\'s Republic of', 'iso' => 'KP']);
        $countries->create(['name' => 'Korea, Republic of', 'iso' => 'KR']);
        $countries->create(['name' => 'Kuwait', 'iso' => 'KW']);
        $countries->create(['name' => 'Kyrgyzstan', 'iso' => 'KG']);
        $countries->create(['name' => 'Lao People\'s Democratic Republic', 'iso' => 'LA']);
        $countries->create(['name' => 'Latvia', 'iso' => 'LV']);
        $countries->create(['name' => 'Lebanon', 'iso' => 'LB']);
        $countries->create(['name' => 'Lesotho', 'iso' => 'LS']);
        $countries->create(['name' => 'Liberia', 'iso' => 'LR']);
        $countries->create(['name' => 'Libya', 'iso' => 'LY']);
        $countries->create(['name' => 'Liechtenstein', 'iso' => 'LI']);
        $countries->create(['name' => 'Lithuania', 'iso' => 'LT']);
        $countries->create(['name' => 'Luxembourg', 'iso' => 'LU']);
        $countries->create(['name' => 'Macao', 'iso' => 'MO']);
        $countries->create(['name' => 'Macedonia, the Former Yugoslav Republic of', 'iso' => 'MK']);
        $countries->create(['name' => 'Madagascar', 'iso' => 'MG']);
        $countries->create(['name' => 'Malawi', 'iso' => 'MW']);
        $countries->create(['name' => 'Malaysia', 'iso' => 'MY']);
        $countries->create(['name' => 'Maldives', 'iso' => 'MV']);
        $countries->create(['name' => 'Mali', 'iso' => 'ML']);
        $countries->create(['name' => 'Malta', 'iso' => 'MT']);
        $countries->create(['name' => 'Marshall Islands', 'iso' => 'MH']);
        $countries->create(['name' => 'Martinique', 'iso' => 'MQ']);
        $countries->create(['name' => 'Mauritania', 'iso' => 'MR']);
        $countries->create(['name' => 'Mauritius', 'iso' => 'MU']);
        $countries->create(['name' => 'Mayotte', 'iso' => 'YT']);
        $countries->create(['name' => 'Mexico', 'iso' => 'MX']);
        $countries->create(['name' => 'Micronesia, Federated States of', 'iso' => 'FM']);
        $countries->create(['name' => 'Moldova, Republic of', 'iso' => 'MD']);
        $countries->create(['name' => 'Monaco', 'iso' => 'MC']);
        $countries->create(['name' => 'Mongolia', 'iso' => 'MN']);
        $countries->create(['name' => 'Montenegro', 'iso' => 'ME']);
        $countries->create(['name' => 'Montserrat', 'iso' => 'MS']);
        $countries->create(['name' => 'Morocco', 'iso' => 'MA']);
        $countries->create(['name' => 'Mozambique', 'iso' => 'MZ']);
        $countries->create(['name' => 'Myanmar', 'iso' => 'MM']);
        $countries->create(['name' => 'Namibia', 'iso' => 'NA']);
        $countries->create(['name' => 'Nauru', 'iso' => 'NR']);
        $countries->create(['name' => 'Nepal', 'iso' => 'NP']);
        $countries->create(['name' => 'Netherlands', 'iso' => 'NL']);
        $countries->create(['name' => 'New Caledonia', 'iso' => 'NC']);
        $countries->create(['name' => 'New Zealand', 'iso' => 'NZ']);
        $countries->create(['name' => 'Nicaragua', 'iso' => 'NI']);
        $countries->create(['name' => 'Niger', 'iso' => 'NE']);
        $countries->create(['name' => 'Nigeria', 'iso' => 'NG']);
        $countries->create(['name' => 'Niue', 'iso' => 'NU']);
        $countries->create(['name' => 'Norfolk Island', 'iso' => 'NF']);
        $countries->create(['name' => 'Northern Mariana Islands', 'iso' => 'MP']);
        $countries->create(['name' => 'Norway', 'iso' => 'NO']);
        $countries->create(['name' => 'Oman', 'iso' => 'OM']);
        $countries->create(['name' => 'Pakistan', 'iso' => 'PK']);
        $countries->create(['name' => 'Palau', 'iso' => 'PW']);
        $countries->create(['name' => 'Palestine, State of', 'iso' => 'PS']);
        $countries->create(['name' => 'Panama', 'iso' => 'PA']);
        $countries->create(['name' => 'Papua New Guinea', 'iso' => 'PG']);
        $countries->create(['name' => 'Paraguay', 'iso' => 'PY']);
        $countries->create(['name' => 'Peru', 'iso' => 'PE']);
        $countries->create(['name' => 'Philippines', 'iso' => 'PH']);
        $countries->create(['name' => 'Pitcairn', 'iso' => 'PN']);
        $countries->create(['name' => 'Poland', 'iso' => 'PL']);
        $countries->create(['name' => 'Portugal', 'iso' => 'PT']);
        $countries->create(['name' => 'Puerto Rico', 'iso' => 'PR']);
        $countries->create(['name' => 'Qatar', 'iso' => 'QA']);
        $countries->create(['name' => 'Réunion', 'iso' => 'RE']);
        $countries->create(['name' => 'Romania', 'iso' => 'RO']);
        $countries->create(['name' => 'Russian Federation', 'iso' => 'RU']);
        $countries->create(['name' => 'Rwanda', 'iso' => 'RW']);
        $countries->create(['name' => 'Saint Barthélemy', 'iso' => 'BL']);
        $countries->create(['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'iso' => 'SH']);
        $countries->create(['name' => 'Saint Kitts and Nevis', 'iso' => 'KN']);
        $countries->create(['name' => 'Saint Lucia', 'iso' => 'LC']);
        $countries->create(['name' => 'Saint Martin (French part)', 'iso' => 'MF']);
        $countries->create(['name' => 'Saint Pierre and Miquelon', 'iso' => 'PM']);
        $countries->create(['name' => 'Saint Vincent and the Grenadines', 'iso' => 'VC']);
        $countries->create(['name' => 'Samoa', 'iso' => 'WS']);
        $countries->create(['name' => 'San Marino', 'iso' => 'SM']);
        $countries->create(['name' => 'Sao Tome and Principe', 'iso' => 'ST']);
        $countries->create(['name' => 'Saudi Arabia', 'iso' => 'SA']);
        $countries->create(['name' => 'Senegal', 'iso' => 'SN']);
        $countries->create(['name' => 'Serbia', 'iso' => 'RS']);
        $countries->create(['name' => 'Seychelles', 'iso' => 'SC']);
        $countries->create(['name' => 'Sierra Leone', 'iso' => 'SL']);
        $countries->create(['name' => 'Singapore', 'iso' => 'SG']);
        $countries->create(['name' => 'Sint Maarten (Dutch part)', 'iso' => 'SX']);
        $countries->create(['name' => 'Slovakia', 'iso' => 'SK']);
        $countries->create(['name' => 'Slovenia', 'iso' => 'SI']);
        $countries->create(['name' => 'Solomon Islands', 'iso' => 'SB']);
        $countries->create(['name' => 'Somalia', 'iso' => 'SO']);
        $countries->create(['name' => 'South Africa', 'iso' => 'ZA']);
        $countries->create(['name' => 'South Georgia and the South Sandwich Islands', 'iso' => 'GS']);
        $countries->create(['name' => 'South Sudan', 'iso' => 'SS']);
        $countries->create(['name' => 'Spain', 'iso' => 'ES']);
        $countries->create(['name' => 'Sri Lanka', 'iso' => 'LK']);
        $countries->create(['name' => 'Sudan', 'iso' => 'SD']);
        $countries->create(['name' => 'Suriname', 'iso' => 'SR']);
        $countries->create(['name' => 'Svalbard and Jan Mayen', 'iso' => 'SJ']);
        $countries->create(['name' => 'Swaziland', 'iso' => 'SZ']);
        $countries->create(['name' => 'Sweden', 'iso' => 'SE']);
        $countries->create(['name' => 'Switzerland', 'iso' => 'CH']);
        $countries->create(['name' => 'Syrian Arab Republic', 'iso' => 'SY']);
        $countries->create(['name' => 'Taiwan', 'iso' => 'TW']);
        $countries->create(['name' => 'Tajikistan', 'iso' => 'TJ']);
        $countries->create(['name' => 'Tanzania, United Republic of', 'iso' => 'TZ']);
        $countries->create(['name' => 'Thailand', 'iso' => 'TH']);
        $countries->create(['name' => 'Timor-Leste', 'iso' => 'TL']);
        $countries->create(['name' => 'Togo', 'iso' => 'TG']);
        $countries->create(['name' => 'Tokelau', 'iso' => 'TK']);
        $countries->create(['name' => 'Tonga', 'iso' => 'TO']);
        $countries->create(['name' => 'Trinidad and Tobago', 'iso' => 'TT']);
        $countries->create(['name' => 'Tunisia', 'iso' => 'TN']);
        $countries->create(['name' => 'Turkey', 'iso' => 'TR']);
        $countries->create(['name' => 'Turkmenistan', 'iso' => 'TM']);
        $countries->create(['name' => 'Turks and Caicos Islands', 'iso' => 'TC']);
        $countries->create(['name' => 'Tuvalu', 'iso' => 'TV']);
        $countries->create(['name' => 'Uganda', 'iso' => 'UG']);
        $countries->create(['name' => 'Ukraine', 'iso' => 'UA']);
        $countries->create(['name' => 'United Arab Emirates', 'iso' => 'AE']);
        $countries->create(['name' => 'United Kingdom', 'iso' => 'GB']);
        $countries->create(['name' => 'United States', 'iso' => 'US']);
        $countries->create(['name' => 'United States Minor Outlying Islands', 'iso' => 'UM']);
        $countries->create(['name' => 'Uruguay', 'iso' => 'UY']);
        $countries->create(['name' => 'Uzbekistan', 'iso' => 'UZ']);
        $countries->create(['name' => 'Vanuatu', 'iso' => 'VU']);
        $countries->create(['name' => 'Venezuela, Bolivarian Republic of', 'iso' => 'VE']);
        $countries->create(['name' => 'Viet Nam', 'iso' => 'VN']);
        $countries->create(['name' => 'Virgin Islands, British', 'iso' => 'VG']);
        $countries->create(['name' => 'Virgin Islands, U.S.', 'iso' => 'VI']);
        $countries->create(['name' => 'Wallis and Futuna', 'iso' => 'WF']);
        $countries->create(['name' => 'Western Sahara', 'iso' => 'EH']);
        $countries->create(['name' => 'Yemen', 'iso' => 'YE']);
        $countries->create(['name' => 'Zambia', 'iso' => 'ZM']);
        $countries->create(['name' => 'Zimbabwe', 'iso' => 'ZW']);
    }
}