version: "3.9"

services:
  db:
    build: .
    restart: always
    ports:
      - 33008:3306
    environment:
      - MYSQL_ROOT_PASSWORD=itMustBeAVeryStrongPassword
      - MYSQL_DATABASE=realise_exo3
      - MYSQL_USER=elyes
      - MYSQL_PASSWORD=12345

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8970:80
    environment:
      - PMA_ARBITRARY=1

#   l5-swagger-app:
#     image: l5-swagger-app
#     container_name: l5-swagger-app
#     restart: "no"
#     build:
#       args:
#         user: l5-swagger
#         uid: 1000
#       context: ./
#       dockerfile: Dockerfile
#       target: local
#     volumes:
#       - l5-swagger-app-volume:/app/l5-swagger-app:rw
#       - ./:/app:rw
#     ports:
#       - "7777:80"

# volumes:
#   l5-swagger-app-volume:

# networks:
#   default:
#     name: l5-swagger-app

