version: "3.7"

services:
  db:
    build: .
    restart: always
    ports:
      - 33008:3306
    environment:
      - MYSQL_ROOT_PASSWORD=itMustBeAVeryStrongPassword
      - MYSQL_DATABASE=realise_exo3
      - MYSQL_USER=elyes
      - MYSQL_PASSWORD=12345

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8970:80
    environment:
      - PMA_ARBITRARY=1

